# Don't print a new line at the start of the prompt
#add_newline = false

# makes prompt a single line
[line_break]
disabled = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[cmd_duration]
#min_time = 2_000  # Show command duration over 10,000 milliseconds (= 2 sec)
format = "took [$duration]($style) "

[character]
#error_symbol = "[X](bold red) "
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"  

# These symbols will only show when battery levels are 20% or less
[battery]
charging_symbol = "⚡️ "
discharging_symbol = "💀 "

[[battery.display]]  # "bold red" style when capacity is between 0% and 20%
threshold = 20 
style = "bold red"

# Clear visibility for exit codes
#[status]
#style = "bg:red"
#symbol = "💣 "
#format = '[\[$symbol$status\]]($style) '
#disabled = false
